kind: Pod
apiVersion: v1
metadata:
 name: pythonpod
spec:
 volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
     claimName: basic
 containers:
  - name: pythonpod
    image: serged/mypython
    command: ["/bin/sh","-c"]
    args: ["ping localhost"]
    volumeMounts:
    - name: task-pv-storage
      mountPath: "/output"
