kind: Pod
apiVersion: v1
metadata:
 name: pythonpod
spec:
 volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
     claimName: basic
 containers:
  - name: pythoncontainer
    image: serged/python
    ports:
    volumeMounts:
    - name: task-pv-storage
      mountPath: "/output"
        
