kind: Pod
apiVersion: v1
metadata:
 name: task-pv-pod
spec:
 volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
     claimName: basic
 containers:
  - name: task-pv-container
    image: nginx
    ports:
    - containerPort: 80
      name: "http-server"
    volumeMounts:
    - name: task-pv-storage
      mountPath: "/output"
        
