apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: test-pv
 labels:
   app: nginxtest
spec:
 replicas: 2
 template:
   metadata:
     labels:
       app: test-pv
       tier: frontend
   spec:
     containers:
     - image: nginx
       name: test-pv 
       ports:
       - containerPort: 80
       volumeMounts:
       - name: task-pv-storage
         mountPath: "/usr/share/nginx/html"

     volumes:
     - name: task-pv-storage
       persistentVolumeClaim:
         claimName: basic1

